### ISSUE TITLE
Audit des erreurs et warnings - 07/09/2021

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#410]
### Erreurs console:
- **Si on recharge la page**
       

     - [ ] Warning: Prop `aria-describedby` did not match. Server: "evergreen-tooltip-2" Client: "evergreen-tooltip-1"
           -> _**Ce problème vient de evergreen qui ne gère pas correctement les `id` des sites SSR. [source](https://github.com/segmentio/evergreen/issues/842)**_
     - [ ] Unable to perform style diff: Unimplemented: setSprite..  Rebuilding the style from scratch.

- **A la création d'une voie métrique**
      
     - [ ] Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
      -> _**Ce problème semble similaire à [celui-ci](https://github.com/visgl/react-map-gl/issues/1171) , pourtant la mise à jour de `react-map-gl` ne corrige pas le message d’erreur. La mise à jour de `react-map-gl-draw`ne corrige pas le problème non plus.**_

- **Lors de la création d’une BAL, lorsque `AlertPublishedBal` s’affiche**_ 
	- [ ] Warning: Failed prop type: Invalid prop `basesLocales` of type `array` supplied to `AlertPublishedBAL`, expected `object`.

- **Accueil**
	- [ ] Pseudo-classe "-webkit-full-screen" inconnu. (Firefox uniquement)
	- [ ] Propriété "-moz-box-shadow" inconnue. (Firefox uniquement)
	- [ ] Propriété "speak" inconnue. (Firefox uniquement)
	- [ ] "Règle keyframe ignorée suite à un mauvais sélecteur." (Firefox uniquement)
	- [ ] "Erreur d’analyse de la valeur pour "grid-template-columns". (Firefox uniquement)

- **Page BasesLocales**
	- [x] Failed prop type: The prop `status` is marked as required in `Publication`, but its value is `undefined`. [#337](https://github.com/etalab/editeur-bal/issues/337)
	- [x] Warning: Failed prop type: Invalid prop `token` of type `boolean` supplied to `Publication`, expected `string`. En mode consultation [#401](https://github.com/etalab/editeur-bal/issues/401) => https://github.com/etalab/editeur-bal/pull/406
	- [x] failed prop type: The prop `baseLocale._id` is marked as required in `Breadcrumb`. [#337](https://github.com/etalab/editeur-bal/issues/337)
	- [x] Warning: The `value` prop is required for the `<Context.Provider>`. Did you misspell it or forget to pass it? [#403](https://github.com/etalab/editeur-bal/issues/403) _**Problème résolu avec la dernière version d’Evergreen [Lien](https://github.com/segmentio/evergreen/issues/1140)**_  
	**RÉSOLU** -> [#414](https://github.com/BaseAdresseNationale/mes-adresses/pull/414)
	
- **Édition numéro**
	- [x] Warning: `value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components. **Corrigé avec [#396](https://github.com/etalab/editeur-bal/pull/396)**
	
- **À l’ouverture de la carte**

     - [x] WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
   -> _**Problème lié à `mapbox-gl-js` et à la "rigueur des développeurs de Firefox". [Source](https://github.com/mapbox/mapbox-gl-js/issues/5292)  (Ne sera pas résolu)**_

- **Page BAL-Demo**:
	_au moment de checher une commune_
	- [x] Warning: componentWillReceiveProps has been renamed, and is not recommended for use.
	**_Ce problème vient d’Evergreen ([Issue similaire](https://github.com/segmentio/evergreen/issues/1053)).
 Problème corrigé avec la dernière version d’Evergreen: [commentaire](https://github.com/segmentio/evergreen/issues/1053#issuecomment-889426645)_** 
          **RÉSOLU** -> [#414](https://github.com/BaseAdresseNationale/mes-adresses/pull/414)

- **Besoin d’aide** :
	- [x] Warning: validateDOMNesting(...): `<p>` cannot appear as a descendant of `<p>`. (Onglet toponyme) [#402](https://github.com/etalab/editeur-bal/issues/402) => https://github.com/etalab/editeur-bal/pull/407
	- [x] Warning: validateDOMNesting(...): `<div>` cannot appear as a descendant of `<p>`. (Onglet base locale) [#402](https://github.com/etalab/editeur-bal/issues/402) => https://github.com/etalab/editeur-bal/pull/407
	- [ ] ~~"Erreur d’analyse de la valeur pour "grid-template-columns". *(pas réussi à reproduire)*~~

- **page /new** :
	- [x] Warning: Invalid DOM property `autocomplete`. Did you mean `autoComplete`?
	- [x] Warning: Prop `autoComplete` did not match. Server: "chrome-off" Client: "off" **(firefox)**
	-  [x] Warning: The `value` prop is required for the `<Context.Provider>`. Did you misspell it or forget to pass it? **(Au moment de faire une recherche dans le champs commune)** [#403](https://github.com/etalab/editeur-bal/issues/403)

- **à l'ouverture de `adress-editor`** :
	- [x] Warning: Failed prop type: The prop `isCertified` is marked as required in `CertificationButton`, but its value is `undefined`. [#404](https://github.com/etalab/editeur-bal/issues/404) => https://github.com/etalab/editeur-bal/pull/408

- **à l’ouverture d’un numéro dans toponyme** :
	- [x] Warning: Failed prop type: Invalid prop `initialValue.voie` of type `object` supplied to `NumeroEditor`, expected `string`. [#405](https://github.com/etalab/editeur-bal/issues/405) => https://github.com/etalab/editeur-bal/pull/409

---

### XO
  **pages/_document.js:44:18**
  -  [ ] ⚠  44:18  Dangerous property dangerouslySetInnerHTML found                                                                                                          react/no-danger
  - [ ]  ⚠  45:18  Dangerous property dangerouslySetInnerHTML found                                                                                                          react/no-danger

  **components/table-row.js:8:29**
  -  [ ] ⚠   8:29  Arrow function has a complexity of 26.                                                                                                                    complexity

  **hooks/key-event.js:10:23**
-  [ ]  ⚠  10:23  React Hook useEffect has a spread element in its dependency array. This means we can't statically verify whether you've passed the correct dependencies.  react-hooks/exhaustive-deps

  **components/bases-locales-list/base-locale-card.js:28:24**
-  [ ]  ⚠  28:24  Arrow function has a complexity of 22.                                                                                                                    complexity

  **components/map/map.js:75:1**
  -  [ ] ⚠  75:1   Function Map has a complexity of 21.                                                                                                                      complexity

  **components/map/hooks/sources.js:92:6**
-  [ ]  ⚠  92:6   React Hook useMemo has a missing dependency: toponyme. Either include it or remove the dependency array.                                                  react-hooks/exhaustive-deps

---

### Erreurs `yarn build`:
-  [ ] Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps` -> https://nextjs.org/docs/messages/opt-out-auto-static-optimization
-  [ ] [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving 'lodash/package.json' in /Users/…/editeur-bal/node_modules/babel-plugin-lodash/lib for build dependencies doesn't lead to expected result '/Users/…/editeur-bal/node_modules/lodash/package.json', but to '/Users/…/editeur-bal/node_modules/babel-plugin-lodash/node_modules/lodash/package.json' instead. Resolving dependencies are ignored for this path.

### Erreurs yarn node 12:
- [ ] warning " > evergreen-ui@6.1.0" has incorrect peer dependency "react@^16.8.0".
- [ ] warning " > evergreen-ui@6.1.0" has incorrect peer dependency "react-dom@^16.8.0".
- [ ] warning "evergreen-ui > react-scrollbar-size@2.1.0" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
- [ ] warning "evergreen-ui > react-tiny-virtual-list@2.2.0" has incorrect peer dependency "react@15.x || 16.x".
- [ ] warning "evergreen-ui > ui-box@4.1.0" has incorrect peer dependency "react@^16.0.0".
- [ ] warning "evergreen-ui > react-scrollbar-size > react-event-listener@0.5.10" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
- [ ] warning " > react-chartjs-2@2.10.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
- [ ] warning " > react-chartjs-2@2.10.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
- [ ] warning "react-map-gl > react-virtualized-auto-sizer@1.0.2" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
- [ ] warning "react-map-gl > react-virtualized-auto-sizer@1.0.2" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
- [ ] warning " > react-map-gl-draw@0.19.2" has incorrect peer dependency "react@^16.x".
- [ ] warning " > react-map-gl-draw@0.19.2" has incorrect peer dependency "react-dom@^16.x".
- [ ] warning " > babel-eslint@10.1.0" has unmet peer dependency "eslint@>= 4.12.1".
- [ ] warning " > eslint-config-xo-nextjs@1.4.0" has unmet peer dependency "eslint@>=5".
- [ ] warning "eslint-config-xo-nextjs > eslint-config-xo-react@0.19.0" has unmet peer dependency "eslint@>=5".
- [ ] warning " > eslint-plugin-react@7.21.5" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
- [ ] warning " > eslint-plugin-react-hooks@4.2.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0".

### Erreurs yarn node 14:
- [ ] warning " > evergreen-ui@6.1.0" has incorrect peer dependency "react@^16.8.0".
- [ ] warning " > evergreen-ui@6.1.0" has incorrect peer dependency "react-dom@^16.8.0".
- [ ] warning "evergreen-ui > react-scrollbar-size@2.1.0" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
- [ ] warning "evergreen-ui > react-tiny-virtual-list@2.2.0" has incorrect peer dependency "react@15.x || 16.x".
- [ ] warning "evergreen-ui > ui-box@4.1.0" has incorrect peer dependency "react@^16.0.0".
- [ ] warning "evergreen-ui > react-scrollbar-size > react-event-listener@0.5.10" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
- [ ] warning " > react-chartjs-2@2.10.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
- [ ] warning " > react-chartjs-2@2.10.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0-beta || ^16.0.0".
- [ ] warning "react-map-gl > react-virtualized-auto-sizer@1.0.2" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
- [ ] warning "react-map-gl > react-virtualized-auto-sizer@1.0.2" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
- [ ] warning " > react-map-gl-draw@0.19.2" has incorrect peer dependency "react@^16.x".
- [ ] warning " > react-map-gl-draw@0.19.2" has incorrect peer dependency "react-dom@^16.x".
- [ ] warning " > babel-eslint@10.1.0" has unmet peer dependency "eslint@>= 4.12.1".
- [ ] warning " > eslint-config-xo-nextjs@1.4.0" has unmet peer dependency "eslint@>=5".
- [ ] warning "eslint-config-xo-nextjs > eslint-config-xo-react@0.19.0" has unmet peer dependency "eslint@>=5".
- [ ] warning " > eslint-plugin-react@7.21.5" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
- [ ] warning " > eslint-plugin-react-hooks@4.2.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0".

---

### Mises à jours disponibles:
- [x] etalab/bal: 1.2.0 -> 1.3.1 ->  ~~_Cette version (1.2.0) est la dernière compatible avec Node 12_~~
- [x] next/bundle-analyzer: 10.0.2 -> 11.1.2
- turf: 6.0.1 || 5.1.5 -> 6.5.0
	- bbox / buffer / center / centroid / difference / length / line-slice
	_turf/difference version 6.0.1 est nécessaire à `react-map-gl-draw`_
- [x] chart.js: 2.9.4 -> 3.5.1
- [x] date-fns: 2.16.1 -> 2.24.0
- [x] evergreen-ui: 6.1.0 -> 6.4.0 
- fuse.js: 3.4.5 -> 6.4.6
- [x] get-stream: 6.0.0 -> 6.0.1
- [x] got: 11.8.0 -> 11.8.2
- ~~immutable: 4.0.0-rc.12 -> 4.0.0-rc.15~~ -> _La dernière version "stable" étant la 3.8.2, il est préférable de ne pas mettre à jour cette librairie_
- [x] lodash: 4.17.20 -> 4.17.21
- [x] next: 11.0.1 -> 11.1.2
- [x] react-chartjs-2: 2.10.0 -> 2.11.1
- [x] react-dropzone: 10.1.10 -> 11.4.2
- [x] react-map-gl: 5.2.7 -> 5.3.17
- [x] react-map-gl-draw: 0.19.2 -> 0.23.8
- use-debounce: 1.1.1 -> 7.0.0

---

### Double appels à API-BAL:
- À l'ouverture d’une BAL:
	- 3 X `GET /v1/bases-locales/6137616c63aad61415eccc1a`
	- 2 X `GET /v1/bases-locales/6137616c63aad61415eccc1a/communes/55326`
	- 2 X `GET /v1/bases-locales/61376a9d569fa016b4227774/communes/55565/voies`
	- 2 X `GET /v1/bases-locales/6137616c63aad61415eccc1a/communes/55326/geojson`
	- 2 X `GET /v1/bases-locales/6137616c63aad61415eccc1a/communes/55326/parcelles`

- À la sélection d’une voie:
	- 3 X `GET /v1/bases-locales/6137616c63aad61415eccc1a`
	- 2 X `GET /v1/bases-locales/6137616c63aad61415eccc1a/communes/55326/geojson`
	- 2 X `GET /v1/bases-locales/6137616c63aad61415eccc1a/communes/55326/parcelles`

- Modification nom de voie:
	- 2 X `GET /v1/bases-locales/61376a9d569fa016b4227774/communes/55565/voies`
	- 2 X `GET /v1/bases-locales/61376a9d569fa016b4227774`

- Sélection d’un toponyme:
	- 3 X `GET /v1/bases-locales/61376a9d569fa016b4227774`

**Comment by tmerlier** [comment]
@GllmR Les avertissements notés ici sont-ils encore d'actualité ?

**Comment by GllmR** [comment]
Les erreurs et avertissements ci dessus ont été corrigé ou ne sont plus présent, je ferme l’issue.
