### ISSUE TITLE
Intégrer les règles de validation du validateur BAL

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/mes-adresses#527]
## Contexte
Le validateur de BAL est actuellement utilisé dans Mes Adresses, mais aucun rapport de son analyse n'est renvoyé à l'utilisateur.

Ce comportement est d'autant plus déroutant au moment de la création d'une BAL via le dépôt d'un fichier CSV car si celui-ci contient des lignes en erreurs, celles-ci seront retirées sans que l'utilisateur en soit averti.

De plus, aucun formulaire (voie, toponyme, numéro, etc) n'est soumis aux règles du validateur. L'API se contente d'appliquer manuellement des règles qui tendent à se rapprocher du validateur. Mais ce fonctionnement a déjà montré ses limites, notamment avec #492.

----

### Création
- [ ] Afficher un rapport de validation compréhensible à la création d’une BAL
- [ ] Proposer dans le rapport, des traitements automatiques, quand cela est possible
- [x] Proposer à l’utilisateur la création de sa BAL en supprimant les lignes en erreur #556

### Édition

- [ ] Regrouper les avertissements dans une vue dédiée permettant de les retrouver et les corriger 
↔️ Évolutions proposées - Tableau de bord de la BAL
- [ ]  Proposer des traitements automatiques quand cela est possible

### Publication

- [ ] Afficher un rapport de validation en cas d’erreur détectée au moment de la publication (pour les BAL déjà créée avec des erreurs - dette technique)

----
## Mise en place graduelle de cette solution

- [x] Afficher un message d’erreur simple lors d’une tentative de publication d’une BAL comportant des erreurs (Quick win ticket voie 3 caractères) BaseAdresseNationale/mes-adresses-api/pull/324
- [x] Afficher un message d’erreur simple lors du dépôt d’un fichier CSV comportant des erreurs. Possible de créer la BAL en avertissant que les erreurs seront retirées (Quick win avertissant les utilisateurs que leur fichier n’est pas conforme et que l’import est donc partiel) #556
- [x] « Brancher » le validateur à la création d’objet voie, toponyme, etc. (Permet d’éviter la création de nouveaux objets non conforme et de renvoyer l’erreur du validateur directement dans le formulaire de l’éditeur) BaseAdresseNationale/mes-adresses-api/pull/336
- [ ] Créer une fenêtre « Rapport du validateur » pouvant être affichée au dépôt d’un fichier, à la publication et dans le tableau de bord de la BAL. (Cette fenêtre pourrait faire l’objet d’un composant réutilisable de la bibliothèque UI afin de le réutiliser sur adresse.data.gouv.fr) #537
