### ISSUE TITLE
Ajouter la langue picarde dans Mes Adresses

### ISSUE THREAD

**Issue by C-Sophie** [BaseAdresseNationale/mes-adresses#743]
A la demande d'un Partenaire de la Charte, Somme numérique, ajouter le code ISO PCD dans l'éditeur Mes Adresses pour que les communes puissent renseigner les adresses en langue picarde.

**Comment by tmerlier** [comment]
## TODO
- [ ] Mettre à jour [le fichier des langues régionales](https://github.com/BaseAdresseNationale/shared-data/blob/master/langues-regionales.json
)
- [ ] Faire une nouvelle release `v1.2.0` de [@etalab/shared-data](https://github.com/BaseAdresseNationale/shared-data)
- [ ] Ajouter le [drapeau de la Picardie](https://fr.wikipedia.org/wiki/Drapeau_de_la_Picardie) sur [Mes Adresses](https://github.com/BaseAdresseNationale/mes-adresses/tree/master/public/static/images/flags) et [adresse.data.gouv.fr](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/tree/master/public/images/icons/flags)
- [ ] Mettre à jour `@etalab/shared-data v1.2.0` sur Mes Adresses et adresse.data.gouv.fr
